/*
 * 抖音开放API
 * douyin open api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for APIResponseExtra
 */
public class APIResponseExtraTest {
    private final APIResponseExtra model = new APIResponseExtra();

    /**
     * Model tests for APIResponseExtra
     */
    @Test
    public void testAPIResponseExtra() {
        // TODO: test APIResponseExtra
    }

    /**
     * Test the property 'logid'
     */
    @Test
    public void logidTest() {
        // TODO: test logid
    }

    /**
     * Test the property 'now'
     */
    @Test
    public void nowTest() {
        // TODO: test now
    }

}
