/*
 * 抖音开放API
 * douyin open api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ConnectReq
 */
public class ConnectReqTest {
    private final ConnectReq model = new ConnectReq();

    /**
     * Model tests for ConnectReq
     */
    @Test
    public void testConnectReq() {
        // TODO: test ConnectReq
    }

    /**
     * Test the property 'clientKey'
     */
    @Test
    public void clientKeyTest() {
        // TODO: test clientKey
    }

    /**
     * Test the property 'responseType'
     */
    @Test
    public void responseTypeTest() {
        // TODO: test responseType
    }

    /**
     * Test the property 'scope'
     */
    @Test
    public void scopeTest() {
        // TODO: test scope
    }

    /**
     * Test the property 'optionalScope'
     */
    @Test
    public void optionalScopeTest() {
        // TODO: test optionalScope
    }

    /**
     * Test the property 'redirectUri'
     */
    @Test
    public void redirectUriTest() {
        // TODO: test redirectUri
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

}
