/*
 * 抖音开放API
 * douyin open api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * APIResponseExtra
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-09-22T12:48:25.482Z[GMT]")
public class APIResponseExtra {
  public static final String SERIALIZED_NAME_LOGID = "logid";
  @SerializedName(SERIALIZED_NAME_LOGID)
  private String logid;

  public static final String SERIALIZED_NAME_NOW = "now";
  @SerializedName(SERIALIZED_NAME_NOW)
  private Long now;


  public APIResponseExtra logid(String logid) {
    
    this.logid = logid;
    return this;
  }

   /**
   * Get logid
   * @return logid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLogid() {
    return logid;
  }


  public void setLogid(String logid) {
    this.logid = logid;
  }


  public APIResponseExtra now(Long now) {
    
    this.now = now;
    return this;
  }

   /**
   * Get now
   * @return now
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getNow() {
    return now;
  }


  public void setNow(Long now) {
    this.now = now;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIResponseExtra apIResponseExtra = (APIResponseExtra) o;
    return Objects.equals(this.logid, apIResponseExtra.logid) &&
        Objects.equals(this.now, apIResponseExtra.now);
  }

  @Override
  public int hashCode() {
    return Objects.hash(logid, now);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIResponseExtra {\n");
    sb.append("    logid: ").append(toIndentedString(logid)).append("\n");
    sb.append("    now: ").append(toIndentedString(now)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

