/*
 * 抖音开放API
 * douyin open api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ConnectReq;
import org.openapitools.client.model.ModelAPIResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OauthApi
 */
@Ignore
public class OauthApiTest {

    private final OauthApi api = new OauthApi();

    
    /**
     * 获取授权码(code)
     *
     * 获取授权码(code)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void connectTest() throws ApiException {
        ConnectReq body = null;
        ModelAPIResponse response = api.connect(body);

        // TODO: test validations
    }
    
}
